version: '3.8'

services:
  mongo_db:
    image: mongo:4.4
    container_name: songs-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - backend_net

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: songs-api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/songs_db
      - FLASK_DEBUG=1
      - FLASK_PORT=5000
      - FLASK_HOST=0.0.0.0
    depends_on:
      - mongo_db
    networks:
      - backend_net
    volumes:
      - .:/app

volumes:
  mongo_data:

networks:
  backend_net:
